// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swrgusctqjrqrkdghtti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3cmd1c2N0cWpycXJrZGdodHRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMDI0MDAsImV4cCI6MjA2OTg3ODQwMH0.kkF_H_Jhvt1oGf9Qbb9tvrPJCezZBpZuaqGRAIjVQB4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
console.log("✅ Connected to Supabase project:", SUPABASE_URL);
